# Numpy 

In [1]:
import numpy as np

## Creating Numpy Arrays 

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([3.14, 4, 3])

array([3.14, 4.  , 3.  ])

In [4]:
np.array([3.13, 4, 5], dtype = int)

array([3, 4, 5])

In [5]:
a1 = np.array([3.14, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [14]:
a1.dtype

dtype('float64')

In [10]:
a2 = np.array([[3.14, 4, 5], [1, 2, 3]]);

In [13]:
a2.shape

(2, 3)

In [15]:
a2.dtype

dtype('float64')

In [18]:
a2.ndim

2

In [20]:
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

In [21]:
a3.ndim

3

In [22]:
a3.shape

(2, 2, 2)

## Creative numpy arrays from Scratch

### `zeros` `ones` `full` `arange` `linspace`

In [23]:
a0 = np.zeros((3, 3, 3))

In [24]:
a0

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
a1 = np.ones([2,3])

In [28]:
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
af = np.full((1,3), 2)

In [31]:
af

array([[2, 2, 2]])

In [34]:
aa = np.arange(2, 10, 2)

In [35]:
aa

array([2, 4, 6, 8])

In [36]:
al = np.linspace(0,1, 5)

In [37]:
al

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### `random`

In [42]:
np.random.random([1,2])

array([[0.67599119, 0.93658354]])

In [44]:
np.random.random([1,2])

array([[0.46512088, 0.2933221 ]])

In [54]:
np.random.seed(10)
np.random.random((2,3))

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])

In [57]:
np.random.normal(0,1,(3,3))

array([[ 0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016],
       [ 2.38496733,  1.12369125,  1.67262221]])

In [58]:
np.random.randint(0, 100, [3,3,3])

array([[[23, 94, 11],
        [28, 74, 88],
        [ 9, 15, 18]],

       [[80, 71, 88],
        [11, 17, 46],
        [ 7, 75, 28]],

       [[33, 84, 96],
        [88, 44,  5],
        [ 4, 71, 88]]])

In [60]:
np.random.rand(2,2,2,2)

array([[[[0.15115202, 0.38411445],
         [0.94426071, 0.98762547]],

        [[0.45630455, 0.82612284],
         [0.25137413, 0.59737165]]],


       [[[0.90283176, 0.53455795],
         [0.59020136, 0.03928177]],

        [[0.35718176, 0.07961309],
         [0.30545992, 0.33071931]]]])

# Array indexing & Slicing

## One-dimension array


In [63]:
x = np.random.randint(20, size = 6)

In [66]:
x

array([14, 16, 10, 17,  0, 17])

In [67]:
x[1]

16

In [68]:
x[2]

10

In [69]:
x[-1]

17

In [72]:
x[0:-1]

array([14, 16, 10, 17,  0])

## Multi-dimension array

In [74]:
x2 = np.random.randint(0, 20, [3,3])

In [75]:
x2

array([[ 9, 16,  9],
       [12, 18, 17],
       [17, 16,  0]])

In [76]:
x2[1,2]

17

In [77]:
x2[1,2] = x2[1,2] +1

In [78]:
x2

array([[ 9, 16,  9],
       [12, 18, 18],
       [17, 16,  0]])

### Slicing

In [80]:
x[0: 5]

array([14, 16, 10, 17,  0])

In [81]:
x[0:-1:2]

array([14, 10,  0])

In [82]:
x[:]

array([14, 16, 10, 17,  0, 17])

In [83]:
x[::-1]

array([17,  0, 17, 10, 16, 14])

In [84]:
x2

array([[ 9, 16,  9],
       [12, 18, 18],
       [17, 16,  0]])

In [90]:
x2[:2,:1:-1]

array([[ 9],
       [18]])

## Reshaping array & Transpose

In [91]:
grid = np.random.randint(1, 20, size = 9)

In [92]:
grid

array([ 6, 10,  1,  7,  1,  3,  4,  4, 19])

In [96]:
grid = grid.reshape((3, 3))

In [95]:
grid

array([[ 6, 10,  1],
       [ 7,  1,  3],
       [ 4,  4, 19]])

In [98]:
grid.T

array([[ 6,  7,  4],
       [10,  1,  4],
       [ 1,  3, 19]])

## Array Concatenation & Splitting

In [99]:
x = np.random.randint(1, 20, 3)

In [100]:
y = np.random.randint(1, 20, 3)

In [104]:
np.concatenate((x,y), axis = 0)

array([14, 12, 17, 14, 12, 18])

In [112]:
x2 = np.random.randint(1, 20, (1,3))

In [113]:
y2 = np.random.randint(1, 20, (2,3))

In [115]:
np.concatenate((x2,y2), axis = 0)

array([[10,  2,  5],
       [ 8,  8, 10],
       [ 8,  1,  4]])

`vstack`

In [118]:
np.vstack((x2, y2))

array([[10,  2,  5],
       [ 8,  8, 10],
       [ 8,  1,  4]])

  `hstack`

In [121]:
a = np.random.randint(1, 20, (3,2))

In [122]:
b = np.random.randint(1,20, (3,4))

In [123]:
np.hstack((a,b))

array([[10, 13, 10,  3,  2, 18],
       [ 5,  7,  7, 11, 14, 12],
       [15, 11,  6, 16, 17, 11]])

### Splitting

In [124]:
x = np.array([1,2,3,99,69,3,2,1])
x1,x2,x3 = np.split(x,(3,5))

In [126]:
x1,x2,x3

(array([1, 2, 3]), array([99, 69]), array([3, 2, 1]))

## Broadcasting & Vectorized Operations

In [127]:
x = np.arange(3) + 5
x

array([5, 6, 7])

In [130]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [134]:
np.arange(3).reshape((3,1)) * np.arange(3)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [146]:
a = np.random.randint(1, 20, [1, 3])
b = np.random.randint(1, 20, [3, 1])

In [147]:
x = a*b

In [148]:
a

array([[18,  2, 12]])

In [149]:
b

array([[15],
       [11],
       [16]])

In [150]:
x

array([[270,  30, 180],
       [198,  22, 132],
       [288,  32, 192]])

## Manipulating & Comparing Arrays

### Aggregation

In [151]:
list_number = [1,2,3]

In [152]:
ll = np.array([list_number])

In [153]:
ll

array([[1, 2, 3]])

In [154]:
sum(list_number)

6

In [155]:
np.sum(ll)

6

In [172]:
mass = np.random.random(10000)

In [173]:
mass.shape

(10000,)

In [174]:
%timeit sum(mass)
%timeit np.sum(mass)

1.19 ms ± 87.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
13.6 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [175]:
np.mean(mass)

0.5007279640900326

In [176]:
np.min(mass)

6.883102653554296e-05

In [177]:
np.max(mass)

0.9998581926431869

## Standard Deviation & Variance

In [178]:
np.std(mass)

0.29111390236211016

In [179]:
np.var(mass)

0.08474730414849621

In [180]:
np.sqrt(np.var(mass))

0.29111390236211016

## Sorting Arrays

In [181]:
x = np.array([4,3,2,5,1])

In [182]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [184]:
np.argsort(x)

array([4, 2, 1, 0, 3], dtype=int64)

## Sorting along columns or rows

In [186]:
MatA = np.random.randint(0, 10, [4,6])


In [187]:
MatA

array([[9, 3, 9, 0, 2, 1],
       [0, 3, 4, 5, 6, 6],
       [6, 5, 8, 6, 2, 6],
       [8, 4, 1, 9, 0, 1]])

In [188]:
np.sort(MatA, axis = 0)

array([[0, 3, 1, 0, 0, 1],
       [6, 3, 4, 5, 2, 1],
       [8, 4, 8, 6, 2, 6],
       [9, 5, 9, 9, 6, 6]])

In [189]:
np.sort(MatA, axis = 1)

array([[0, 1, 2, 3, 9, 9],
       [0, 3, 4, 5, 6, 6],
       [2, 5, 6, 6, 6, 8],
       [0, 1, 1, 4, 8, 9]])

## Linear Algebra

In [195]:
a = np.arange(1, 10).reshape((3,3))

In [196]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
b = np.arange(1,7).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [199]:
a.dot(b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [200]:
a @ b

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

## Dot Product Example


In [204]:
np.random.seed(1)
sales_amounts = np.random.randint(20, size = (5,3))

In [205]:
sales_amounts

array([[ 5, 11, 12],
       [ 8,  9, 11],
       [ 5, 15,  0],
       [16,  1, 12],
       [ 7, 13,  6]])

In [206]:
import pandas as pd

In [208]:
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thur", "Fri"], columns = ["Butter", "Cake", "Milk"])

In [209]:
weekly_sales

Butter  Cake  Milk
Mon        5    11    12
Tues       8     9    11
Wed        5    15     0
Thur      16     1    12
Fri        7    13     6

In [213]:
prices = np.array([5,10,3])

In [214]:
Prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns = ["Butter", "Cake", "Milk"])

In [215]:
Prices

Butter  Cake  Milk
Price       5    10     3

In [218]:
weekly_sales["Total Price"] = sales_amounts.dot(prices)

In [219]:
weekly_sales

Butter  Cake  Milk  total_price  Total Price
Mon        5    11    12          171          171
Tues       8     9    11          163          163
Wed        5    15     0          175          175
Thur      16     1    12          126          126
Fri        7    13     6          183          183